// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDPgD0m4-whCMQpcvEhkxS6k0MRX3a51QU',
    appId: '1:616449335266:web:6a9f5bc03e6163e7fbe3bb',
    messagingSenderId: '616449335266',
    projectId: 'lackstage',
    authDomain: 'lackstage.firebaseapp.com',
    storageBucket: 'lackstage.appspot.com',
    measurementId: 'G-KZ5ZTT14LM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8RpKZFB5bEuaca2D4-Vvq9CKNaA5gEx0',
    appId: '1:616449335266:android:0483f8ad70f85668fbe3bb',
    messagingSenderId: '616449335266',
    projectId: 'lackstage',
    storageBucket: 'lackstage.appspot.com',
  );
}
